
const database = [
    //customer account
    {
        id: "1000000",
        username: "username1",
        password: "password1@",
        fullname: "Nguyễn Văn Anh",
        email: "nguyenvananh@gmail.com",
        phoneNum: "0923236277",
        gender: "Nam",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",

    },
    {
        id: "1000001",
        username: "username2",
        password: "password2@",
        fullname: "Nguyễn Huy Quốc",
        email: "nguyenhuyquoc@gmail.com",
        phoneNum: "0923236277",
        gender: "Nam",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",
    },
    {
        id: "1000002",
        username: "username3",
        password: "password3@",
        fullname: "Hà Huy Nam",
        email: "hahuynam@gmail.com",
        phoneNum: "0923236277",
        gender: "Nam",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",
    },
    {
        id: "1000003",
        username: "username4",
        password: "password4@",
        fullname: "Nguyễn Văn Anh",
        email: "nguyenvananh@gmail.com",
        phoneNum: "0923236277",
        gender: "Nam",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",
    },
    {
        id: "1000004",
        username: "username5",
        password: "password5@",
        fullname: "Châu Ngọc Anh",
        email: "chaungocanh@gmail.com",
        phoneNum: "0923236277",
        gender: "Nữ",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",
    },
    {
        id: "1000005",
        username: "username6",
        password: "password6@",
        fullname: "Phan Hà Anh",
        email: "phanhaanh@gmail.com",
        phoneNum: "0923236277",
        gender: "Nam",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",
    },
    {
        id: "1000006",
        username: "username7",
        password: "password7@",
        fullname: "Nguyễn Hà Phương",
        email: "nguyenhaphuong@gmail.com",
        phoneNum: "0923236277",
        gender: "Nam",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",
    },
    {
        id: "1000007",
        username: "username8",
        password: "password8@",
        fullname: "Nguyễn Đình Phúc",
        email: "nguyendinhphuc@gmail.com",
        phoneNum: "0923236277",
        gender: "Nam",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",
    },
    {
        id: "1000008",
        username: "username9",
        password: "password9@",
        fullname: "Nguyễn Hà Giang",
        email: "nguyenhagiang@gmail.com",
        phoneNum: "0923236277",
        gender: "Nam",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",
    },
    {
        id: "1000009",
        username: "username10",
        password: "password10@",
        fullname: "Dương Đình Bảo",
        email: "duongdinhbao@gmail.com",
        phoneNum: "0923236277",
        gender: "Nam",
        birthDate: "20020217",
        registerDate: "20221205",
        address: "Phường Linh Trung, Thủ Đức, TPHCM",
    },
];
export default database;